In [120]:
# importing libraries
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd


In [121]:
# importing datasets
data_set = pd.read_csv('../../dataset/LinearRegression/50_Startups.csv')
# Extracting independent and dependent variables
x = data_set.iloc[:, :-1].values
y = data_set.iloc[:, 4].values
data_set.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [122]:
# Categorical Data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_x = LabelEncoder()
x[:, 3] = labelencoder_x.fit_transform(x[:, 3])
ct = ColumnTransformer([('onthot', OneHotEncoder(), [3])], remainder='passthrough')
x = ct.fit_transform(x)
nm.set_printoptions(suppress=True)
x[:5]

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

In [123]:
# remote multicollinearity
x = x[:, 1:]
x[:5]

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

In [124]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1/5, random_state=0)
print(x_test[:5])
y_test[:5]

[[1.0 0.0 66051.52 182645.56 118148.2]
 [0.0 0.0 100671.96 91790.61 249744.55]
 [1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 27892.92 84710.77 164470.71]
 [1.0 0.0 153441.51 101145.55 407934.54]]


array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39])

In [125]:
# Fitting the MLR model to the dataset
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)
x_pred = regressor.predict(x_train)
y_pred = regressor.predict(x_test)
print(y_train[:5])
print(x_pred[:5])
print('Train Score: ', regressor.score(x_train, y_train))
print(y_test[:5])
print(y_pred[:5])
print('Test Score: ', regressor.score(x_test, y_test))


[ 96778.92  96479.51 105733.54  96712.8  124266.9 ]
[ 95764.42320496  89164.62849777 109506.72329086  91366.21889409
 127111.48666646]
[103282.38 144259.4  146121.95  77798.83 191050.39]
[103015.20159796 132582.27760816 132447.73845175  71976.09851259
 178537.48221054]
